### ISSUE TITLE
Will it work with static?

### ISSUE THREAD

**Issue by pozitron57** [josephernest/TinyAnalytics#11]
Will TinyAnalytics work if the tracking code is placed into static `.html` files? I made an initial setup and have `TinyAnalytics` working and counting visitors at `mysite.com/index.php`, which I created specifically for testing purposes. I placed the tracking code also to my `.html` files but it doesn't seem to be working.

By the way, noticed a few bugs in docs: 

1. Password is set on line 8 of `index.php`, not 5 as it said in `README.md`,
2. the tracking code is not visible on the [main page](https://github.com/josephernest/TinyAnalytics) for some reason, only in [raw](https://raw.githubusercontent.com/josephernest/TinyAnalytics/master/README.md) ([see screenshot](http://i.imgur.com/n8CAbge.png)).

**Comment by josephernest** [comment]
Thank you for your feedback! I just fixed the doc :)

> Will TinyAnalytics work if the tracking code is placed into static .html files?

No, it works in PHP, so it won't work in static HTML files.
