### ISSUE TITLE
Wordpress

### ISSUE THREAD

**Issue by johntunnel** [josephernest/TinyAnalytics#12]
Looks like adding the code to functions.php is really, really bad idea. 
Breaks the site. 
Any recommendations how to add to wordpress?

**Comment by benyafai** [comment]
It would be better to add to your header.php or footer.php - something that is always loaded when a user visits the site.

**Comment by johntunnel** [comment]
It was better. Only frontpage was out, I could still control the backpage. :)
But the solution does not work. I do not know why. I use "-" inside the directory name in line "include". 
I chenges ' to ", added ( and ). Nothing. 
Only two lines of code ?!

**Comment by benyafai** [comment]
Yes, only the two lines required, just make sure that the include goes to the correct location.
If your Wordpress and TinyAnalytics folders are in the same directory then you could possibly use:
```
include '../../../TinyAnalytics/tracker.php';
record_visit('mywebsite');
```
The `..` part says to go up a folder
assuming this is put in /wordpress/wp-content/themes/yourtheme/footer.php

**Comment by johntunnel** [comment]
My code is:
`<?php 
include '/wp-content/uploads/tinyanalytics/tracker.php';
record_visit('myownsitename');
?>`
Above I put into header and footer.
In the functions.php I put without <?php and without ?> , in the header and footer I put 100% same as above. 
Should I put before or after body in the header.php?
Should I put before or after /body in the footer.php?
Header.php also has head and html
Footer also has /html 
Any suggestions?

**Comment by benyafai** [comment]
The code should only be loaded once, so only header *or* footer will work
It can be loaded anywhere (before or after `<body>`) as the PHP doesn't load anything on the user's screen, it only uses the HTTP request information.

**Comment by johntunnel** [comment]
I managed with this one:
include ($_SERVER["DOCUMENT_ROOT"] . "/wp-content/uploads/tinyanalitics/tracker.php");
