### ISSUE TITLE
Try if it works on a low-end shared hosting

### ISSUE THREAD

**Issue by josephernest** [josephernest/TinyAnalytics#8]
Todo.

Do low-end shared hosting offer the possibility to run a Python script?

**Comment by roooareee** [comment]
Hi, would you class [this](https://www.blacknight.com/minimus-hosting.html) as low-end?

It's what I'm using, but I'm struggling to get TinyAnalytics working.

I get this error message:

• No analytics data yet. Add this tracking code in your website's main PHP file, and then visit it at least once.

```
<?php
include '/var/www/vhosts/xx/xxxxxx/webspace/httpdocs/singsite.com/TinyAnalytics/tracker.php';
record_visit('mywebsite');
?>
```

Should 'mywebsite' be changed to something else? I've tried numerous variations on to path to the site.

BTW, I'm also using and loving void for this site.

**Comment by josephernest** [comment]
You probably don't have Python on your hosting, can you ask your hosting provider?

If not, this is one more argument for doing this: https://github.com/josephernest/TinyAnalytics/issues/5

Oh, this is cool about void :)

**Comment by roooareee** [comment]
Cheers, yes, quite possibly no python, I've opened a ticket, we'll see what they say.

**Comment by roooareee** [comment]
So my hosting does include Python, either 2.4.3 or 2.3.4, not sure which. It all lives in a CGI-bin. I can get as far as logging into index.php, but then I get 403 forbidden. I've altered permissions, to no effect. Any ideas? I'm also waiting to hear from the hosting company.

**Comment by markallasread** [comment]
@roooareee: Check your error logs if they're made available to you. Sounds like a simple permissions issue, less so than a problem running it.

**Comment by roooareee** [comment]
It appears to be this : attempt to invoke directory as script

`[Fri Feb 24 16:19:13 2017] [error] [client 79.97.xxx.xxx] attempt to invoke directory as script: /var/www/vhosts/xx/xxxxxx/webspace/cgi-bin/TinyAnalytics/, referer: http://singsite.com/cgi-bin/TinyAnalytics/index.php`

Seems to be a common problem, but I'm not sure I have the ability to alter Apache scripts, or if I understand completely what's wrong...

**Comment by josephernest** [comment]
Unfortunately, no idea... Maybe you could ask on StackOverflow?
